import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThePanelHeader from "./_components/TheHeader";
import BottomNavigation from "./_components/BottomNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <div className="max-w-7xl mx-auto bg-linear-to-b from-gray-50 to-orange p-4 md:p-6 pb-26 min-h-dvh">
            <ThePanelHeader />
            {children}
          </div>
          <BottomNavigation />
      </body>
    </html>
  );
}
