import { Metadata } from "next";
import TheHeader from "../_components/TheHeader";
import BottomNavigation from "../_components/BottomNavigation";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <div className="max-w-7xl mx-auto bg-linear-to-b from-gray-50 to-orange p-4 md:p-6 pb-26 min-h-dvh">
        <TheHeader />
        {children}
      </div>
      <BottomNavigation />
    </>
  );
}